//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBanc.Utils.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemaBanc.Utils.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presento un Error al Cargar los datos del objeto..
        /// </summary>
        public static string ErrorCargarDatos {
            get {
                return ResourceManager.GetString("ErrorCargarDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {{&apos;visa&apos;: &apos;{0}&apos;, &apos;master&apos;: &apos;{1}&apos;, &apos;diners&apos;: &apos;{2}&apos;, &apos;american&apos;: &apos;{3}&apos;, &apos;discover&apos;: &apos;{4}&apos;}}.
        /// </summary>
        public static string JSONMensajesFranquicia {
            get {
                return ResourceManager.GetString("JSONMensajesFranquicia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visa|Master Card|American Express|Diners Club|Discover.
        /// </summary>
        public static string ListaFranquicias {
            get {
                return ResourceManager.GetString("ListaFranquicias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enero|Febrero|Marzo|Abril|Mayo|Junio|Julio|Agosto|Septiembre|Octubre|Noviembre|Diciembre.
        /// </summary>
        public static string ListaMeses {
            get {
                return ResourceManager.GetString("ListaMeses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [&quot;Afganistan&quot;, 
        ///&quot;Albania&quot;, 
        ///&quot;Alemania&quot;, 
        ///&quot;Andorra&quot;, 
        ///&quot;Angola&quot;, 
        ///&quot;Antartida&quot;, 
        ///&quot;Antigua y Barbuda&quot;, 
        ///&quot;Arabia Saudi&quot;, 
        ///&quot;Argelia&quot;, 
        ///&quot;Argentina&quot;, 
        ///&quot;Armenia&quot;, 
        ///&quot;Australia&quot;, 
        ///&quot;Austria&quot;, 
        ///&quot;Azerbaiyan&quot;, 
        ///&quot;Bahamas&quot;, 
        ///&quot;Bahrain&quot;, 
        ///&quot;Bangladesh&quot;, 
        ///&quot;Barbados&quot;, 
        ///&quot;Belgica&quot;, 
        ///&quot;Belice&quot;, 
        ///&quot;Benin&quot;, 
        ///&quot;Bermudas&quot;, 
        ///&quot;Bielorrusia&quot;, 
        ///&quot;Birmania Myanmar&quot;, 
        ///&quot;Bolivia&quot;, 
        ///&quot;Bosnia y Herzegovina&quot;, 
        ///&quot;Botswana&quot;, 
        ///&quot;Brasil&quot;, 
        ///&quot;Brunei&quot;, 
        ///&quot;Bulgaria&quot;, 
        ///&quot;Burkina Faso&quot;, 
        ///&quot;Burundi&quot;, 
        ///&quot;Butan&quot;, 
        ///&quot;Cabo Verde&quot;, 
        ///&quot;Camboya [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string ListaPaises {
            get {
                return ResourceManager.GetString("ListaPaises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crédito.
        /// </summary>
        public static string ListaTipoTarjeta {
            get {
                return ResourceManager.GetString("ListaTipoTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la inserción de la auditoría de forma correcta..
        /// </summary>
        public static string MensajeAuditoriaIngresoSuccess {
            get {
                return ResourceManager.GetString("MensajeAuditoriaIngresoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se encontró el registro {0}..
        /// </summary>
        public static string MensajeBusquedaEntidadSuccess {
            get {
                return ResourceManager.GetString("MensajeBusquedaEntidadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el registro solicitado..
        /// </summary>
        public static string MensajeBusquedaEntidadWarning {
            get {
                return ResourceManager.GetString("MensajeBusquedaEntidadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo destinado ha sido enviado..
        /// </summary>
        public static string MensajeCorreoEnviado {
            get {
                return ResourceManager.GetString("MensajeCorreoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo no ha podido ser enviado..
        /// </summary>
        public static string MensajeCorreoError {
            get {
                return ResourceManager.GetString("MensajeCorreoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se relizó la inserción de la empresa de forma correcta..
        /// </summary>
        public static string MensajeEmpresaSuccess {
            get {
                return ResourceManager.GetString("MensajeEmpresaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la inserción de la encuesta de forma correcta..
        /// </summary>
        public static string MensajeEncuestaSuccess {
            get {
                return ResourceManager.GetString("MensajeEncuestaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al guardar la encuesta..
        /// </summary>
        public static string MensajeErrorEncuesta {
            get {
                return ResourceManager.GetString("MensajeErrorEncuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al guardar una opción de una pregunta de la encuesta..
        /// </summary>
        public static string MensajeErrorOpcion {
            get {
                return ResourceManager.GetString("MensajeErrorOpcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al guardar una pregunta de la encuesta..
        /// </summary>
        public static string MensajeErrorPregunta {
            get {
                return ResourceManager.GetString("MensajeErrorPregunta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la inserción del ítem del plan de forma correcta..
        /// </summary>
        public static string MensajeItemPlanSuccess {
            get {
                return ResourceManager.GetString("MensajeItemPlanSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la inserción del ítem de la pregunta de forma correcta.
        /// </summary>
        public static string MensajeItemPreguntaSuccess {
            get {
                return ResourceManager.GetString("MensajeItemPreguntaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se encontraron {0} registros..
        /// </summary>
        public static string MensajeListaSuccess {
            get {
                return ResourceManager.GetString("MensajeListaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron registros..
        /// </summary>
        public static string MensajeListaWarning {
            get {
                return ResourceManager.GetString("MensajeListaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ingresado no coincide con la contraseña o no existe..
        /// </summary>
        public static string MensajeLoginError {
            get {
                return ResourceManager.GetString("MensajeLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso exitoso.
        /// </summary>
        public static string MensajeLoginSuccess {
            get {
                return ResourceManager.GetString("MensajeLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la inserción del control de forma correcta..
        /// </summary>
        public static string MensajeMetadataSuccess {
            get {
                return ResourceManager.GetString("MensajeMetadataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la inserción del pago de forma correcta..
        /// </summary>
        public static string MensajePagoPlanSuccess {
            get {
                return ResourceManager.GetString("MensajePagoPlanSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El párametro se encuentra nulo..
        /// </summary>
        public static string MensajeParametroWarning {
            get {
                return ResourceManager.GetString("MensajeParametroWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la inserción del plan de la empresa de forma correcta..
        /// </summary>
        public static string MensajePlanEmpresaSuccess {
            get {
                return ResourceManager.GetString("MensajePlanEmpresaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la inserción del plan de forma correcta..
        /// </summary>
        public static string MensajePlanSuccess {
            get {
                return ResourceManager.GetString("MensajePlanSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la inserción del precio de forma correcta..
        /// </summary>
        public static string MensajePrecioSuccess {
            get {
                return ResourceManager.GetString("MensajePrecioSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la inserción de la pregunta de forma correcta..
        /// </summary>
        public static string MensajePreguntaSuccess {
            get {
                return ResourceManager.GetString("MensajePreguntaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se presento un error en la insercion de la respuesta.
        /// </summary>
        public static string MensajeRespuestaFail {
            get {
                return ResourceManager.GetString("MensajeRespuestaFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la inserción de la respuesta de forma correcta.
        /// </summary>
        public static string MensajeRespuestaSuccess {
            get {
                return ResourceManager.GetString("MensajeRespuestaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la inserción del rol de forma correcta..
        /// </summary>
        public static string MensajeRolSuccess {
            get {
                return ResourceManager.GetString("MensajeRolSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la inserción del usuario de forma correcta..
        /// </summary>
        public static string MensajeUsuarioSuccess {
            get {
                return ResourceManager.GetString("MensajeUsuarioSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se Presento Un Error Al eliminar la Encuesta.
        /// </summary>
        public static string MessageDeleteEncuestaFailed {
            get {
                return ResourceManager.GetString("MessageDeleteEncuestaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La encuesta se ha eliminado Correctamente..
        /// </summary>
        public static string MessageDeleteEncuestaSuccess {
            get {
                return ResourceManager.GetString("MessageDeleteEncuestaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ValidacionErrorTarjetaAmerican.
        /// </summary>
        public static string nombreRecursoAE {
            get {
                return ResourceManager.GetString("nombreRecursoAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ValidacionErrorTarjetaDiscover.
        /// </summary>
        public static string nombreRecursoDC {
            get {
                return ResourceManager.GetString("nombreRecursoDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ValidacionErrorTarjetaDiners.
        /// </summary>
        public static string nombreRecursoDI {
            get {
                return ResourceManager.GetString("nombreRecursoDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ValidacionErrorTarjetaMaster.
        /// </summary>
        public static string nombreRecursoMC {
            get {
                return ResourceManager.GetString("nombreRecursoMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ValidacionErrorTarjetaVisa.
        /// </summary>
        public static string nombreRecursoVI {
            get {
                return ResourceManager.GetString("nombreRecursoVI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las tarjetas American Express comienzan con el número 3 y contienen 15 dígitos..
        /// </summary>
        public static string ValidacionErrorTarjetaAmerican {
            get {
                return ResourceManager.GetString("ValidacionErrorTarjetaAmerican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las tarjetas Diners pueden comenzar por los números 3 o 6 y contienen 16 dígitos..
        /// </summary>
        public static string ValidacionErrorTarjetaDiners {
            get {
                return ResourceManager.GetString("ValidacionErrorTarjetaDiners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las tarjetas Discover pueden comenzar por los números 3 o 6 y contienen 16 dígitos..
        /// </summary>
        public static string ValidacionErrorTarjetaDiscover {
            get {
                return ResourceManager.GetString("ValidacionErrorTarjetaDiscover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las tarjetas Master Card comienzan por el número 2 o 5 y contienen 16 dígitos..
        /// </summary>
        public static string ValidacionErrorTarjetaMaster {
            get {
                return ResourceManager.GetString("ValidacionErrorTarjetaMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las tarjetas Visa comienzan por el número 4 y contienen 16 dígitos..
        /// </summary>
        public static string ValidacionErrorTarjetaVisa {
            get {
                return ResourceManager.GetString("ValidacionErrorTarjetaVisa", resourceCulture);
            }
        }
    }
}
